# Repository settings managed by Probot Settings app
# https://github.com/apps/settings
# The app syncs settings automatically on push to this file

repository:
  name: wedding-gallery
  description: Wedding photo gallery with HLS video support
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true

  # Merge settings - disable all merge methods to prevent accidental SHA changes
  # Use CLI for fast-forward merges to keep branches in sync
  allow_merge_commit: false  # No merge commits
  allow_squash_merge: false  # No squash
  allow_rebase_merge: false  # No rebase (creates new SHAs)

branches:
  - name: main
    protection:
      # Require status checks to pass before merging
      required_status_checks:
        strict: true
        contexts:
          - "test"

      # Require linear history (fast-forward only)
      required_linear_history: true

      # No PR reviews required on main (single developer)
      required_pull_request_reviews: null

      # Enforce on admins (prevents accidental pushes, use break glass if needed)
      enforce_admins: true

      # No restrictions on who can push
      restrictions: null

      # No force pushes
      allow_force_pushes: false

      # No deletions
      allow_deletions: false

  - name: release
    protection:
      # Require status checks to pass before merging
      required_status_checks:
        strict: true
        contexts:
          - "test"

      # Require linear history (fast-forward only)
      required_linear_history: true

      # No PR requirement (single developer - can't self-approve)
      # Use PRs as best practice, but rely on tests + linear history
      required_pull_request_reviews: null

      # Enforce on admins (prevents accidental pushes, use break glass if needed)
      enforce_admins: true

      # No restrictions
      restrictions: null

      # No force pushes to release
      allow_force_pushes: false

      # No deletions
      allow_deletions: false
